config/routes.rb
Rails.application.routes.draw do
  get 'contacts/list'
  get 'contacts/:id' => 'contacts#view', :as => :contacts_view
  post 'contacts/:id' => 'contacts#send_sms'
  root 'contacts#list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include HTTParty
  @@options = {query: {
    'token' => SKIPIO_API_KEY
    }}
  def list
    response = self.class.get('https://stage.skipio.com/api/v2/contacts',
    @@options)
    @contacts = response['data']
  end

  def view
    id = params['id']
    response = self.class.get("https://stage.skipio.com/api/v2/contacts/#{id}",
    @@options)
    if response.response.code == "404"
      raise ActionController::RoutingError.new('Not Found')
    end
    @contact = response['data']
  end

  def send_sms
    id = params['id']
    payload = {recipients: ["contact-#{id}"],
    message: {
      body: "Test message"
      }}.to_json
    response = self.class.post("https://stage.skipio.com/api/v2/messages",
      :body => payload,
      :headers => {'Content-Type' => 'application/json' },
      :query => {'token' => SKIPIO_API_KEY}
    )
    if response.response.code != "201"
      raise ActionController::RoutingError.new('Could not send')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/list.html.erb
<h1>My Contacts</h1>

<% @contacts.each do |contact| %>
<a href="<%=contacts_view_url(contact['id'])%>"><h3><%=contact['full_name']%></h3></a>
<p>

<% end %>

app/views/contacts/send_sms.html.erb
<h1>Message Sent!</h1>

app/views/contacts/view.html.erb
<h1><%= @contact['full_name']%></h1>
<dl>
  <dt>E-mail</dt>
  <dd><%=@contact['email']%></dd>
  <dt>Mobile Phone</dt>
  <dd><%=@contact['phone_mobile']%></dd>
</dl>
<h3>Send Message:</h3>
<%= form_tag do %>
  <%= label_tag(:msg, "Message:") %>
  <%= text_area_tag(:msg) %>
  <%= submit_tag("Send") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skipio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>